; Math module doc-check: expected values follow the v2 documentation
; (https://www.autohotkey.com/docs/v2/lib/Math.htm and each function page).
#Requires AutoHotkey v2.0

MsgBox "Abs_int=" Abs(-5)
MsgBox "Abs_float=" Abs(-5.5)
MsgBox "Sqrt=" Sqrt(16)
MsgBox "Sqrt2=" (Sqrt(2) > 1.4)
MsgBox "Mod_pos=" Mod(7, 3)
MsgBox "Mod_neg=" Mod(-7, 3)      ; result takes the sign of the dividend
MsgBox "Mod_float=" Mod(7.5, 2)   ; supports floats
MsgBox "Round_int=" Round(3.14159, 2)
MsgBox "Round_float=" Round(3.14159)
MsgBox "Round_neg=" Round(-3.6)
MsgBox "Floor=" Floor(3.7)
MsgBox "Ceil=" Ceil(3.2)
MsgBox "Min=" Min(3, 1, 2)
MsgBox "Max=" Max(3, 1, 2)
MsgBox "Min_str=" Min("10", "9")  ; numeric strings compared numerically
MsgBox "Exp=" Exp(0)
MsgBox "Ln=" Ln(1)
MsgBox "Log=" Log(100)
MsgBox "Sin=" Sin(0)
MsgBox "Cos=" Cos(0)
MsgBox "Tan=" Tan(0)
MsgBox "ASin=" ASin(0)
MsgBox "ACos=" ACos(1)
MsgBox "ATan=" ATan(0)
MsgBox "ATan2=" ATan(0)
MsgBox "Random_in_range=" (Random(1, 10) >= 1 && Random(1, 10) <= 10)
MsgBox "Random_seed=" (Random(5, 5))
MsgBox "IsNumber=" IsNumber("3.5")
MsgBox "IsInteger=" IsInteger(3)
MsgBox "IsInteger_float=" IsInteger(3.0)
MsgBox "IsFloat=" IsFloat(3.5)
MsgBox "IsAlnum=" IsAlnum("A")
MsgBox "IsDigit=" IsDigit("5")
MsgBox "IsAlpha=" IsAlpha("a")
MsgBox "IsUpper=" IsUpper("A")
MsgBox "IsLower=" IsLower("a")
MsgBox "IsSpace=" IsSpace(" ")
MsgBox "IsXDigit=" IsXDigit("F")
MsgBox "IsTime=" IsTime("20240101120000")
MsgBox "Type_int=" Type(1)
MsgBox "Type_float=" Type(1.5)
MsgBox "Type_str=" Type("x")
MsgBox "Type_obj=" Type({})
MsgBox "Type_arr=" Type([])
