#!/usr/bin/env python3
"""Generate the Linux input capability table from input_caps.def.

Usage:
  python3 tools/gen_input_caps.py          # update linux-port.htm
  python3 tools/gen_input_caps.py --check  # fail if the generated block drifted
"""
from __future__ import annotations

import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source/linux/core/input_caps.def"
HEADER = ROOT / "source/linux/core/input_backend.h"
DOC = ROOT / "docs-v2/docs/linux-port.htm"
BEGIN = "<!-- INPUT_CAPS:BEGIN -->"
END = "<!-- INPUT_CAPS:END -->"

FIELDS = [
    "kind", "name", "global_hotkeys", "suppress", "passthrough", "key_up",
    "wildcard", "bare_keys", "zero_confirm", "dynamic", "multi_owner",
    "scan_code", "custom_combo", "char_stream", "synthetic_provenance",
    "send_level_gate", "injection_unicode",
]
BOOL_FIELDS = set(FIELDS[2:14] + FIELDS[15:])


def parse_caps() -> list[dict[str, str]]:
    text = SOURCE.read_text(encoding="utf-8")
    entries: list[dict[str, str]] = []
    for match in re.finditer(r"AHK_INPUT_CAPS\((.*?)\)", text, re.S):
        raw = re.sub(r"//.*", "", match.group(1))
        values = [part.strip() for part in raw.split(",") if part.strip()]
        if len(values) != len(FIELDS):
            raise SystemExit(f"bad input_caps.def entry ({len(values)} fields): {values}")
        entry = dict(zip(FIELDS, values))
        entry["name"] = entry["name"].strip('"')
        entries.append(entry)
    if not entries:
        raise SystemExit("no AHK_INPUT_CAPS entries found")
    return entries


def caps_version() -> str:
    text = HEADER.read_text(encoding="utf-8")
    match = re.search(r"AHK_INPUT_CAPS_VERSION\s*=\s*(\d+)", text)
    if not match:
        raise SystemExit("AHK_INPUT_CAPS_VERSION not found")
    return match.group(1)


def display(field: str, value: str) -> str:
    if field in BOOL_FIELDS:
        return "yes" if value == "true" else "no"
    if field == "synthetic_provenance":
        return value.lower()
    return value


def generated_block() -> str:
    entries = parse_caps()
    columns = [
        ("name", "Backend"), ("global_hotkeys", "Global"),
        ("suppress", "Suppress"), ("passthrough", "~ pass"),
        ("key_up", "Key-up"), ("wildcard", "Wildcard"),
        ("bare_keys", "Bare"), ("zero_confirm", "Zero-confirm"),
        ("dynamic", "Dynamic"), ("multi_owner", "Multi-owner"),
        ("scan_code", "Scan code"), ("custom_combo", "Custom combo"),
        ("char_stream", "Character stream"),
        ("synthetic_provenance", "Provenance"),
        ("send_level_gate", "SendLevel gate"),
        ("injection_unicode", "Direct Unicode"),
    ]
    lines = [
        BEGIN,
        "<!-- Generated by tools/gen_input_caps.py; do not edit this block. -->",
        f'<p>Capability schema: <code>caps_version={caps_version()}</code>. '
        "The values below are implementation capabilities, not current health. "
        "Query <code>HotkeyBackendGet()</code> for state, generation, coverage, "
        "route guarantees and compatibility outcome.</p>",
        "<table>",
        "  <tr>" + "".join(f"<th>{html.escape(title)}</th>" for _, title in columns) + "</tr>",
    ]
    for entry in entries:
        cells = "".join(
            f"<td>{html.escape(display(field, entry[field]))}</td>"
            for field, _ in columns
        )
        lines.append(f"  <tr>{cells}</tr>")
    lines.extend([
        "</table>",
        "<p><code>heuristic</code> provenance means process-local/device heuristics; "
        "only a future broker/compositor-stamped origin may claim "
        "<code>authoritative</code>. A <code>no</code> value remains no until a matching "
        "behavior test is added.</p>",
        END,
    ])
    return "\n".join(lines)


def replace_block(text: str, block: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit(f"missing {BEGIN}/{END} markers in {DOC}")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    return pattern.sub(block, text, count=1)


def main() -> int:
    check = "--check" in sys.argv[1:]
    original = DOC.read_text(encoding="utf-8")
    expected = replace_block(original, generated_block())
    if check:
        if expected != original:
            print("input capability documentation is stale", file=sys.stderr)
            return 1
        print("input capability documentation: up to date")
        return 0
    DOC.write_text(expected, encoding="utf-8")
    print(f"updated {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
