#!/usr/bin/env python3
# gen_parity.py -- regenerate source/linux/parity_data.h from
# tests/doccheck/parity.tsv (check_detail0821 §13).
#
# parity.tsv columns: name<TAB>level<TAB>note  (lines starting with '#' or
# blank lines are ignored).  level is P1/P2/P3/P4.  Functions not listed
# default to P1 compatible at runtime.
#
# Usage:
#   python3 tools/gen_parity.py            # rewrite parity_data.h in place
#   python3 tools/gen_parity.py --check    # exit non-zero if the header is stale

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TSV = os.path.join(REPO, "tests", "doccheck", "parity.tsv")
OUT = os.path.join(REPO, "source", "linux", "parity_data.h")

LEVELS = {"P1": 1, "P2": 2, "P3": 3, "P4": 4}


def load():
    entries = []
    with open(TSV, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                print("parity.tsv: bad line: %r" % line, file=sys.stderr)
                sys.exit(1)
            name, level = parts[0].strip(), parts[1].strip()
            note = parts[2].strip() if len(parts) > 2 else ""
            if level not in LEVELS:
                print("parity.tsv: bad level %r for %s" % (level, name), file=sys.stderr)
                sys.exit(1)
            entries.append((name, LEVELS[level], note))
    entries.sort(key=lambda e: e[0].lower())
    return entries


def render(entries):
    lines = [
        "// AUTO-GENERATED by tools/gen_parity.py from tests/doccheck/parity.tsv --",
        "// do not edit by hand.  Parity classification for the Linux port",
        "// (check_detail0821 §13): P1 compatible (default), P2 adapted,",
        "// P3 simulated, P4 unavailable.",
        "#pragma once",
        "",
        "struct LinuxParityEntry",
        "{",
        "\tconst char *name;",
        "\tint level;      // 1..4 (P1..P4).",
        "\tconst char *note;",
        "};",
        "",
        "// Sorted by name (case-insensitive); a function not present here is P1.",
        "static const LinuxParityEntry kLinuxParity[] =",
        "{",
    ]
    for name, level, note in entries:
        esc_note = note.replace("\\", "\\\\").replace('"', '\\"')
        lines.append("\t{ \"%s\", %d, \"%s\" }," % (name, level, esc_note))
    lines += [
        "};",
        "static const int kLinuxParityCount = (int)(sizeof(kLinuxParity) / sizeof(kLinuxParity[0]));",
        "",
    ]
    return "\n".join(lines)


def main():
    entries = load()
    text = render(entries)
    if "--check" in sys.argv:
        if os.path.isfile(OUT) and open(OUT, encoding="utf-8").read() == text:
            print("parity_data.h: up to date (%d entries)" % len(entries))
            return 0
        print("parity_data.h is STALE (run tools/gen_parity.py)", file=sys.stderr)
        return 1
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d entries)" % (OUT, len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
