// AUTO-GENERATED by tools/gen_parity.py from tests/doccheck/parity.tsv --
// do not edit by hand.  Parity classification for the Linux port
// (check_detail0821 §13): P1 compatible (default), P2 adapted,
// P3 simulated, P4 unavailable.
#pragma once

struct LinuxParityEntry
{
	const char *name;
	int level;      // 1..4 (P1..P4).
	const char *note;
};

// Sorted by name (case-insensitive); a function not present here is P1.
static const LinuxParityEntry kLinuxParity[] =
{
	{ "ComCall", 4, "No COM vtable on Linux: raises \"Invalid arg type.\" / \"Invalid parameter #1\" (no runnable implementation)" },
	{ "ComObjActive", 2, "COM is a D-Bus adaptation: ComObjActive is approximated by ComObjGet" },
	{ "ComObjArray", 4, "SafeArray has no Linux counterpart: raises an explicit not-ported error" },
	{ "ComObjConnect", 4, "COM event sink has no Linux counterpart: raises an explicit not-ported error" },
	{ "ComObject", 2, "COM is a D-Bus adaptation: no IUnknown/IDispatch pointers; ComObject maps to a D-Bus service proxy" },
	{ "ComObjFlags", 2, "COM is a D-Bus adaptation: flags operate on the D-Bus wrapper, not a COM object" },
	{ "ComObjFromPtr", 2, "COM is a D-Bus adaptation: the pointer is treated as an opaque D-Bus handle" },
	{ "ComObjGet", 2, "COM is a D-Bus adaptation: ComObjGet creates a proxy for a D-Bus service" },
	{ "ComObjQuery", 4, "IUnknown/IID query has no Linux counterpart: raises an explicit not-ported error" },
	{ "ComObjType", 2, "COM is a D-Bus adaptation: 'IID' returns a \"(D-Bus)\" placeholder" },
	{ "ComObjValue", 2, "COM is a D-Bus adaptation: returns the opaque D-Bus handle value" },
	{ "ComValue", 2, "COM is a D-Bus adaptation: wraps typed values for the D-Bus layer" },
	{ "ControlGetChecked", 3, "Control checked state is a local shadow; external X changes are not read back" },
	{ "ControlGetEnabled", 3, "Control enabled state is a local shadow; external X changes are not read back" },
	{ "ControlGetExStyle", 3, "Control style is a local shadow; external X changes are not read back" },
	{ "ControlGetStyle", 3, "Control style is a local shadow; external X changes are not read back" },
	{ "ControlSetChecked", 3, "Control checked state is a local shadow; external X changes are not read back" },
	{ "ControlSetEnabled", 3, "Control enabled state is a local shadow; external X changes are not read back" },
	{ "ControlSetExStyle", 3, "Control style is a local shadow; external X changes are not read back" },
	{ "ControlSetStyle", 3, "Control style is a local shadow; external X changes are not read back" },
	{ "Download", 2, "Uses curl/wget; requires the external tool" },
	{ "DriveEject", 2, "Uses eject/udisksctl; requires the external tool" },
	{ "DriveGetCapacity", 2, "Uses lsblk/df; requires the external tool" },
	{ "DriveGetFilesystem", 2, "Uses lsblk; requires the external tool" },
	{ "DriveGetList", 2, "Uses lsblk; requires the external tool" },
	{ "DriveGetSpaceFree", 2, "Uses lsblk/df; requires the external tool" },
	{ "DriveGetStatus", 2, "Uses lsblk/udisksctl; requires the external tool" },
	{ "DriveGetType", 2, "Uses lsblk; requires the external tool" },
	{ "DriveLock", 2, "Uses udisksctl; requires the external tool" },
	{ "DriveRetract", 2, "Uses eject/udisksctl; requires the external tool" },
	{ "DriveSetLabel", 2, "Uses lsblk/e2label; requires the external tool" },
	{ "DriveUnlock", 2, "Uses udisksctl; requires the external tool" },
	{ "FileCreateShortcut", 2, "Uses .desktop/.url instead of .lnk (icon index / run state fields defaulted)" },
	{ "FileGetShortcut", 2, "Reads .desktop/.url instead of .lnk (documented field semantics)" },
	{ "InstallKeybdHook", 3, "Records a boolean only; no low-level hook is installed" },
	{ "InstallMouseHook", 3, "Records a boolean only; no low-level hook is installed" },
	{ "KeyWait", 3, "XQueryKeymap polling; logical/physical state and debounce are approximate" },
	{ "MenuSelect", 4, "Targets a Win32 menu that does not exist: raises an explicit error" },
	{ "MonitorGetWorkArea", 3, "Approximate via XRandR/Xinerama (single-screen fallback)" },
	{ "OnMessage", 4, "No Win32 message system on X11: monitors are stored but nothing is delivered" },
	{ "PostMessage", 4, "No Win32 message system on X11: raises the documented error / returns 0" },
	{ "RegCreateKey", 3, "Registry is a single-user INI file; no system-wide/permission/32-64 view semantics" },
	{ "RegDelete", 3, "Registry is a single-user INI file; no system-wide/permission/32-64 view semantics" },
	{ "RegDeleteKey", 3, "Registry is a single-user INI file; no system-wide/permission/32-64 view semantics" },
	{ "RegRead", 3, "Registry is a single-user INI file (~/.config/autohotkey-registry.txt); all hives normalized into it" },
	{ "RegWrite", 3, "Registry is a single-user INI file; no system-wide/permission/32-64 view semantics" },
	{ "RunAs", 4, "No logon API: Run/RunWait raise \"Launch Error (possibly related to RunAs)\"" },
	{ "SendInput", 2, "XTEST batch without a journal; hook-unload self-suppression implemented, target delivery limited by the passive grab" },
	{ "SendMessage", 4, "No Win32 message system on X11: raises the documented error / returns 0" },
	{ "SendPlay", 2, "No X11 journal: SendEvent pacing + the SetKeyDelay ,, Play variants (injection depth equals Event)" },
	{ "SoundBeep", 2, "Terminal/X11 bell; Frequency is ignored (no pitch control)" },
	{ "SoundGetMute", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "SoundGetName", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "SoundGetType", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "SoundGetVolume", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "SoundPlay", 2, "Uses paplay/aplay; requires the external tool and a sound server" },
	{ "SoundSetMute", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "SoundSetVolume", 2, "Uses pactl/amixer; requires the external tool; limited to master devices" },
	{ "TraySetIcon", 2, "Delivered as a StatusNotifierItem (org.kde.StatusNotifierItem + com.canonical.dbusmenu); the menu is the script's A_TrayMenu (customizable) with default Pause/Suspend/Reload/Exit when empty; no watcher is a silent no-op" },
	{ "TrayTip", 2, "Delivered as an org.freedesktop.Notifications notification (per-desktop daemon); empty TrayTip is a no-op" },
	{ "WinGetExStyle", 3, "Window style is a virtual shadow + EWMH; exact for self-set windows only" },
	{ "WinGetStyle", 3, "Window style is a virtual shadow + EWMH; exact for self-set windows only" },
	{ "WinGetTransparent", 3, "Window transparency is a virtual shadow + _NET_WM_WINDOW_OPACITY; external windows not guaranteed" },
	{ "WinSetAlwaysOnTop", 3, "Virtual shadow + _NET_WM_STATE_ABOVE sent to the WM" },
	{ "WinSetExStyle", 3, "Window style is a virtual shadow + EWMH; exact for self-set windows only" },
	{ "WinSetStyle", 3, "Window style is a virtual shadow + EWMH; exact for self-set windows only" },
	{ "WinSetTransColor", 3, "The TransColor color-key concept has no X11 equivalent (approximated)" },
	{ "WinSetTransparent", 3, "Window transparency is a virtual shadow + _NET_WM_WINDOW_OPACITY; external windows not guaranteed" },
};
static const int kLinuxParityCount = (int)(sizeof(kLinuxParity) / sizeof(kLinuxParity[0]));
